name: Docker Image Builder
run-name: Image built by @${{ github.actor }}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        # Build Push Action @ version 3
        uses: docker/build-push-action@37abcedcc1da61a57767b7588cb9d03eb57e28b3
        with:
          push: true
          tags: |
            vocovo/docker-mosquitto:latest
            vocovo/docker-mosquitto:${{ github.sha }}
            vocovo/docker-mosquitto:${{ github.ref_name }}
