name: Build versioned image
run-name: Build versioned image by @${{ github.actor }}

on:
  push:
    tags:
      - v**

defaults:
  run:
    shell: bash

jobs:
  build_image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Get docker image tag
        id: docker-image-tag
        run: |
          sha_short=$(git rev-parse --short HEAD)
          timestamp=$(date +'%Y%m%d-%H%M%S')
          mosquitto_version="2.0.18"
          sha_tag="${mosquitto_version}-${sha_short}"
          timestamp_tag="${mosquitto_version}-${timestamp}"
          echo "Docker image tags are ${sha_tag} and ${timestamp_tag}"
          echo "sha_tag=${sha_tag}" >>"${GITHUB_OUTPUT}"
          echo "timestamp_tag=${timestamp_tag}" >>"${GITHUB_OUTPUT}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            "vocovo/docker-mosquitto:${{ steps.docker-image-tag.outputs.sha_tag }}"
            "vocovo/docker-mosquitto:${{ steps.docker-image-tag.outputs.timestamp_tag }}"
