name: Build versioned image
run-name: Build versioned image by @${{ github.actor }}

on:
  push:
    tags:
      - v**

defaults:
  run:
    shell: bash

jobs:
  build_image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Get docker image tag
        id: docker-image-tag
        run: |
          ref='${{ github.ref_name }}'
          echo "Tag ref is ${ref}"
          # replace any characters not permitted in a docker tag with an underscore
          tag="${ref//[^A-Za-z0-9\.\-_]/_}"
          echo "Sanitised tag ref is ${tag}"
          echo "tag=${tag}" >>"${GITHUB_OUTPUT}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            "vocovo/docker-mosquitto:${{ steps.docker-image-tag.outputs.tag }}"
